    1. Explain three-dimensional data indexing.

In [2]:
import numpy as np
x = np.arange(1,46).reshape(3,3,5)
x

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]]])

--> We can access each two dimensional arrays in it with simple indexing as follows:

In [3]:
print('First 2D Array\n',x[0],'\n')
print('Second 2D Array\n',x[1],'\n')
print('Third 2D Array\n',x[2])

First 2D Array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

Second 2D Array
 [[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

Third 2D Array
 [[31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]]


--> Now we will print the second row of first two-dimensional array

In [4]:
print('First 2D Array\n',x[0][1],'\n')

First 2D Array
 [ 6  7  8  9 10] 



--> Now we will print particular item from the array

In [12]:
print('First 2D Array\n',x[0][1][1],'\n')

First 2D Array
 7 



--> Final Conclusion,x[0][1][1] means

        x[0] --> select array 
        x[x][1] --> select array with row number
        x[x][1][1] --> select array with row number and column number

    2. What's the difference between a series and a dataframe?

--> Series is a type of list which can take integer values, string values, double value and more. Series can only contain single list with index, whereas dataframes can be made of more than one series or we can say that a dataframes is a collection of series that can be used to analyse the data.

    3. What role does pandas play in data cleaning?

--> Pandas offer a diverse range of built-in functions that can be used to clean and manipulate datasets prior to analysis. It can allow you to drop incomplete rows and columns, fill missing values and improve the readability of the dataset through category renaming.


    4. How do you use pandas to make a data frame out of n-dimensional arrays?

--> We will use following method 

pd.DataFrame(data=''name of array'', index=''list of row names'',column = ''list of column names'' )

    5. Explain the notion of pandas plotting.

    -->'bar' or 'barh' for bar plots.
    -->'hist' for histogram.
    -->'box' for boxplot.
    -->'kde' or 'density' for density plots.
    -->'area' for area plots.
    -->'scatter' for scatter plots.
    -->'hexbin' for hexagonal bin plots.
    -->'pie' for pie plots.
